class Constants {
  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "Physics": [
      {
        'id': 'mech',
        'title': 'Mechanics',
        'tier': 'free',
        'topics': [
          "Motion (kinematics, velocity, acceleration)",
          "Forces, Newton's Laws, friction",
          "Work, energy, and power",
          "Gravitation and projectile motion",
          "Momentum and collisions",
        ],
      },
      {
        'id': 'thermo',
        'title': 'Thermodynamics',
        'tier': 'free',
        'topics': [
          "Laws of thermodynamics",
          "Heat transfer (conduction, convection, radiation)",
          "Thermal expansion and specific heat",
          "Heat engines and entropy",
        ],
      },
      {
        'id': 'elec',
        'title': 'Electromagnetism',
        'tier': 'free',
        'topics': [
          "Electric fields and circuits (Ohm's Law, resistors, capacitors)",
          "Magnetism and electromagnetic induction",
          "AC/DC circuits",
          "Electromagnetic waves",
        ],
      },
      {
        'id': 'waves',
        'title': 'Waves and Optics',
        'tier': 'free',
        'topics': [
          "Properties of waves (frequency, wavelength)",
          "Sound waves and Doppler effect",
          "Light (reflection, refraction, lenses)",
          "Interference and diffraction",
        ],
      },
      {
        'id': 'mod',
        'title': 'Modern Physics',
        'tier': 'vip',
        'topics': [
          "Quantum mechanics (photoelectric effect, Bohr model)",
          "Nuclear physics (radioactivity, fission, fusion)",
          "Special relativity (time dilation, mass-energy equivalence)",
          "Semiconductors and diodes",
        ],
      },
      {
        'id': 'appl',
        'title': 'Applied Physics',
        'tier': 'vip',
        'topics': [
          "Simple machines (levers, pulleys)",
          "Fluid dynamics (Bernoulli's principle)",
          "Basics of astrophysics (black holes, cosmic rays)",
        ],
      },
    ],
    "Chemistry": [
      {
        'id': 'phys',
        'title': 'Physical Chemistry',
        'tier': 'free',
        'topics': [
          "Atomic structure (electron configuration)",
          "Chemical bonding (ionic, covalent, metallic)",
          "States of matter (gas laws, phase changes)",
          "Reaction rates and equilibrium",
        ],
      },
      {
        'id': 'inorg',
        'title': 'Inorganic Chemistry',
        'tier': 'free',
        'topics': [
          "Periodic table trends (electronegativity, ionization energy)",
          "Acids, bases, and salts",
          "Redox reactions",
          "Coordination compounds",
        ],
      },
      {
        'id': 'org',
        'title': 'Organic Chemistry',
        'tier': 'free',
        'topics': [
          "Hydrocarbons (alkanes, alkenes, alkynes)",
          "Functional groups (alcohols, carboxylic acids)",
          "IUPAC nomenclature",
          "Polymers and biomolecules (proteins, carbohydrates)",
        ],
      },
      {
        'id': 'analy',
        'title': 'Analytical Chemistry',
        'tier': 'free',
        'topics': [
          "Stoichiometry and mole concept",
          "Titration and pH calculations",
          "Chromatography and spectroscopy",
        ],
      },
      {
        'id': 'env',
        'title': 'Environmental Chemistry',
        'tier': 'vip',
        'topics': [
          "Pollution (air, water, soil)",
          "Greenhouse gases and ozone layer",
          "Green chemistry principles",
        ],
      },
      {
        'id': 'applied',
        'title': 'Applied Chemistry',
        'tier': 'vip',
        'topics': [
          "Industrial processes (Haber process, electrolysis)",
          "Everyday chemistry (soaps, detergents)",
          "Nanotechnology and materials science",
        ],
      },
    ],
    "Biology": [
      {
        'id': 'cell',
        'title': 'Cell Biology',
        'tier': 'free',
        'topics': [
          "Cell structure (organelles, prokaryotic vs. eukaryotic)",
          "Cell division (mitosis, meiosis)",
          "Photosynthesis and cellular respiration",
          "Transport across membranes (diffusion, osmosis)",
        ],
      },
      {
        'id': 'gene',
        'title': 'Genetics',
        'tier': 'free',
        'topics': [
          "DNA structure and replication",
          "Mendelian inheritance (Punnett squares)",
          "Genetic mutations and disorders",
          "CRISPR and biotechnology",
        ],
      },
      {
        'id': 'evol',
        'title': 'Evolution',
        'tier': 'free',
        'topics': [
          "Natural selection and adaptation",
          "Evidence for evolution (fossils, homologous structures)",
          "Speciation and genetic drift",
          "Human evolution",
        ],
      },
      {
        'id': 'human',
        'title': 'Human Physiology',
        'tier': 'free',
        'topics': [
          "Digestive, circulatory, and respiratory systems",
          "Nervous system and neurotransmitters",
          "Endocrine system (hormones)",
          "Immune system (vaccines, antibodies)",
        ],
      },
      {
        'id': 'eco',
        'title': 'Ecology',
        'tier': 'vip',
        'topics': [
          "Ecosystems (food chains, energy pyramids)",
          "Biodiversity and conservation",
          "Biogeochemical cycles (carbon, nitrogen)",
          "Climate change impacts",
        ],
      },
      {
        'id': 'micro',
        'title': 'Microbiology & Biotechnology',
        'tier': 'vip',
        'topics': [
          "Bacteria, viruses, and fungi",
          "Fermentation and antibiotics",
          "Genetic engineering (GMOs)",
          "Stem cells and cloning",
        ],
      },
    ],
    "Astronomy": [
      {
        'id': 'planet',
        'title': 'Planetary Science',
        'tier': 'free',
        'topics': [
          "Planets and moons (terrestrial vs. gas giants)",
          "Asteroids, comets, and meteoroids",
          "Solar system formation",
          "Kepler's laws of planetary motion",
        ],
      },
      {
        'id': 'stellar',
        'title': 'Stellar Astronomy',
        'tier': 'free',
        'topics': [
          "Star formation and classification (H-R diagram)",
          "Stellar evolution (white dwarfs, neutron stars)",
          "Supernovae and nucleosynthesis",
          "Binary star systems",
        ],
      },
      {
        'id': 'galaxy',
        'title': 'Galaxies and Cosmology',
        'tier': 'free',
        'topics': [
          "Galaxy types (spiral, elliptical, irregular)",
          "Cosmic microwave background",
          "Big Bang theory",
          "Dark matter and dark energy",
        ],
      },
      {
        'id': 'space',
        'title': 'Space Exploration',
        'tier': 'free',
        'topics': [
          "Space missions (Apollo, Voyager)",
          "Telescopes (optical, radio, space-based)",
          "Rockets and propulsion systems",
          "International Space Station",
        ],
      },
      {
        'id': 'astrochem',
        'title': 'Astrochemistry',
        'tier': 'vip',
        'topics': [
          "Interstellar medium composition",
          "Molecular clouds and star formation",
          "Spectroscopy in astronomy",
        ],
      },
      {
        'id': 'astrophys',
        'title': 'Astrophysics',
        'tier': 'vip',
        'topics': [
          "Gravitational waves",
          "Black hole physics",
          "Relativity in astrophysics",
          "Cosmic rays and particle physics",
        ],
      },
      {
        'id': 'exoplanet',
        'title': 'Exoplanets',
        'tier': 'vip',
        'topics': [
          "Exoplanet detection methods (transit, radial velocity)",
          "Habitability zones",
          "Exoplanet atmospheres",
        ],
      },
      {
        'id': 'celmech',
        'title': 'Celestial Mechanics',
        'tier': 'vip',
        'topics': [
          "Orbital dynamics (elliptical orbits)",
          "Tides and gravitational interactions",
          "N-body problem",
          "Lagrange points",
        ],
      },
    ],
    "Mathematics": [
      {
        'id': 'algebra',
        'title': 'Algebra',
        'tier': 'free',
        'topics': [
          "Linear equations and inequalities",
          "Quadratic equations",
          "Matrices and determinants",
          "Functions and graphs",
        ],
      },
      {
        'id': 'geom',
        'title': 'Geometry',
        'tier': 'free',
        'topics': [
          "Euclidean geometry (triangles, circles)",
          "Coordinate geometry",
          "Theorems (Pythagoras, Thales)",
          "3D geometry",
        ],
      },
      {
        'id': 'calc',
        'title': 'Calculus',
        'tier': 'free',
        'topics': [
          "Limits and continuity",
          "Derivatives and applications",
          "Integrals (definite, indefinite)",
          "Differential equations",
        ],
      },
      {
        'id': 'stats',
        'title': 'Statistics and Probability',
        'tier': 'free',
        'topics': [
          "Descriptive statistics (mean, median, mode)",
          "Probability distributions",
          "Hypothesis testing",
          "Combinatorics",
        ],
      },
      {
        'id': 'numtheory',
        'title': 'Number Theory',
        'tier': 'vip',
        'topics': [
          "Prime numbers and divisibility",
          "Modular arithmetic",
          "Diophantine equations",
          "Fermat's little theorem",
        ],
      },
      {
        'id': 'trig',
        'title': 'Trigonometry',
        'tier': 'vip',
        'topics': [
          "Trigonometric functions (sine, cosine)",
          "Trigonometric identities",
          "Applications in triangles",
          "Polar coordinates",
        ],
      },
      {
        'id': 'model',
        'title': 'Mathematical Modeling',
        'tier': 'vip',
        'topics': [
          "Linear and exponential models",
          "Population dynamics",
          "Optimization problems",
          "Physics-based modeling",
        ],
      },
      {
        'id': 'logic',
        'title': 'Logic and Set Theory',
        'tier': 'vip',
        'topics': [
          "Propositional logic",
          "Set operations (union, intersection)",
          "Proof techniques (induction, contradiction)",
          "Cardinality and infinity",
        ],
      },
    ],
    "Earth Science": [
      {
        'id': 'geo',
        'title': 'Geology',
        'tier': 'free',
        'topics': [
          "Rock cycle (igneous, sedimentary, metamorphic)",
          "Mineral properties",
          "Plate tectonics",
          "Earthquakes and volcanoes",
        ],
      },
      {
        'id': 'meteo',
        'title': 'Meteorology',
        'tier': 'free',
        'topics': [
          "Weather patterns (fronts, pressure systems)",
          "Climate zones",
          "Atmospheric layers",
          "Weather forecasting",
        ],
      },
      {
        'id': 'ocean',
        'title': 'Oceanography',
        'tier': 'free',
        'topics': [
          "Ocean currents and circulation",
          "Marine ecosystems",
          "Tides and waves",
          "Ocean floor topography",
        ],
      },
      {
        'id': 'envproc',
        'title': 'Environmental Processes',
        'tier': 'free',
        'topics': [
          "Soil formation and types",
          "Hydrologic cycle",
          "Natural disasters (tsunamis, hurricanes)",
          "Erosion and sedimentation",
        ],
      },
      {
        'id': 'paleo',
        'title': 'Paleontology',
        'tier': 'vip',
        'topics': [
          "Fossils and dating methods",
          "Extinction events",
          "Dinosaur classification",
          "Paleoclimate studies",
        ],
      },
      {
        'id': 'geoeng',
        'title': 'Geological Engineering',
        'tier': 'vip',
        'topics': [
          "Geothermal energy extraction",
          "Mining techniques",
          "Seismic surveying",
          "Groundwater management",
        ],
      },
    ],
    "Computer Science": [
      {
        'id': 'algo',
        'title': 'Algorithms',
        'tier': 'free',
        'topics': [
          "Sorting algorithms (bubble, merge)",
          "Search algorithms (binary, linear)",
          "Time complexity (Big-O notation)",
          "Graph algorithms",
        ],
      },
      {
        'id': 'prog',
        'title': 'Programming Concepts',
        'tier': 'free',
        'topics': [
          "Variables and data types",
          "Control structures (loops, conditionals)",
          "Functions and recursion",
          "Object-oriented programming",
        ],
      },
      {
        'id': 'ai',
        'title': 'Artificial Intelligence',
        'tier': 'free',
        'topics': [
          "Machine learning basics",
          "Neural networks",
          "Natural language processing",
          "AI ethics",
        ],
      },
      {
        'id': 'data',
        'title': 'Data Structures',
        'tier': 'free',
        'topics': [
          "Arrays and linked lists",
          "Stacks and queues",
          "Trees and graphs",
          "Hash tables",
        ],
      },
      {
        'id': 'cyber',
        'title': 'Cybersecurity',
        'tier': 'vip',
        'topics': [
          "Encryption methods (RSA, AES)",
          "Network security",
          "Malware and viruses",
          "Ethical hacking",
        ],
      },
      {
        'id': 'hard',
        'title': 'Computer Hardware',
        'tier': 'vip',
        'topics': [
          "CPU and memory architecture",
          "Logic gates",
          "Storage devices (HDD, SSD)",
          "Input/output systems",
        ],
      },
    ],
    "Engineering": [
      {
        'id': 'mech',
        'title': 'Mechanical Engineering',
        'tier': 'free',
        'topics': [
          "Mechanics of materials",
          "Thermodynamics in machines",
          "Kinematics of machinery",
          "Fluid mechanics",
        ],
      },
      {
        'id': 'elec',
        'title': 'Electrical Engineering',
        'tier': 'free',
        'topics': [
          "Circuit analysis (Kirchhoff's laws)",
          "Semiconductors",
          "Power systems",
          "Signal processing",
        ],
      },
      {
        'id': 'civil',
        'title': 'Civil Engineering',
        'tier': 'free',
        'topics': [
          "Structural analysis",
          "Bridge and building design",
          "Geotechnical engineering",
          "Transportation systems",
        ],
      },
      {
        'id': 'chem',
        'title': 'Chemical Engineering',
        'tier': 'free',
        'topics': [
          "Chemical reactors",
          "Mass transfer",
          "Thermodynamics in chemical processes",
          "Polymer engineering",
        ],
      },
      {
        'id': 'robo',
        'title': 'Robotics',
        'tier': 'vip',
        'topics': [
          "Robot kinematics",
          "Control systems",
          "Sensors and actuators",
          "Autonomous systems",
        ],
      },
      {
        'id': 'mater',
        'title': 'Materials Science',
        'tier': 'vip',
        'topics': [
          "Material properties (strength, ductility)",
          "Nanomaterials",
          "Composites",
          "Corrosion and degradation",
        ],
      },
    ],
    "Environmental Science": [
      {
        'id': 'eco',
        'title': 'Ecosystems',
        'tier': 'free',
        'topics': [
          "Food webs and trophic levels",
          "Biomes (forests, deserts)",
          "Biodiversity metrics",
          "Ecological succession",
        ],
      },
      {
        'id': 'clim',
        'title': 'Climate Change',
        'tier': 'free',
        'topics': [
          "Greenhouse effect",
          "Global warming impacts",
          "Climate modeling",
          "Carbon footprint",
        ],
      },
      {
        'id': 'sustain',
        'title': 'Sustainability',
        'tier': 'free',
        'topics': [
          "Sustainable development goals",
          "Circular economy",
          "Resource management",
          "Eco-friendly technologies",
        ],
      },
      {
        'id': 'renew',
        'title': 'Renewable Energy',
        'tier': 'free',
        'topics': [
          "Solar and wind energy",
          "Hydropower",
          "Biofuels",
          "Energy storage systems",
        ],
      },
      {
        'id': 'conserv',
        'title': 'Conservation',
        'tier': 'vip',
        'topics': [
          "Wildlife conservation strategies",
          "Protected areas",
          "Endangered species",
          "Restoration ecology",
        ],
      },
      {
        'id': 'pollut',
        'title': 'Pollution Control',
        'tier': 'vip',
        'topics': [
          "Air and water pollution",
          "Waste management",
          "Toxicology",
          "Environmental regulations",
        ],
      },
    ],
    "History of Science": [
      {
        'id': 'ancient',
        'title': 'Ancient Science',
        'tier': 'free',
        'topics': [
          "Greek astronomy (Ptolemy, Aristotle)",
          "Ancient medicine",
          "Early mathematics (Euclid)",
          "Alchemy origins",
        ],
      },
      {
        'id': 'medieval',
        'title': 'Medieval Science',
        'tier': 'free',
        'topics': [
          "Islamic Golden Age contributions",
          "Medieval astronomy (Copernicus precursors)",
          "Scholasticism",
          "Early optics",
        ],
      },
      {
        'id': 'modern',
        'title': 'Modern Science',
        'tier': 'free',
        'topics': [
          "Scientific Revolution (Galileo, Newton)",
          "Industrial Revolution technologies",
          "Electromagnetism discovery",
          "Theory of evolution",
        ],
      },
      {
        'id': 'discov',
        'title': 'Key Discoveries',
        'tier': 'free',
        'topics': [
          "Relativity theory",
          "Quantum mechanics",
          "DNA structure",
          "Space race milestones",
        ],
      },
      {
        'id': 'scientists',
        'title': 'Famous Scientists',
        'tier': 'vip',
        'topics': [
          "Newton's laws",
          "Marie Curie's radioactivity",
          "Einstein's contributions",
          "Turing's computing",
        ],
      },
      {
        'id': 'milestones',
        'title': 'Scientific Milestones',
        'tier': 'vip',
        'topics': [
          "Invention of the microscope",
          "Periodic table development",
          "Penicillin discovery",
          "Internet creation",
        ],
      },
    ],
  };
}
